### ISSUE TITLE
App Crashed when click links on View of tuyasmart-bizbundle-device_activator

### ISSUE THREAD

**Issue by tanshuai** [tuya/tuya-ui-bizbundle-android-demo#14]
App Crashed when click links on View of tuyasmart-bizbundle-device_activator, all other features are working well.

Crashed if click on Red Areas.

![image](https://user-images.githubusercontent.com/3947852/112433547-603d7180-8d7d-11eb-8a9f-c67dad5ccd87.png)

## API Versions
```
        implementation 'com.tuya.smart:tuyasmart:3.24.0'
        implementation 'com.tuya.smart:tuyasmart-bizbundle-device_activator:3.22.0-9'
```

## Errors Log
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: camapp.csfe.com, PID: 22633
    android.view.InflateException: Binary XML file line #17 in camapp.csfe.com:layout/abc_action_menu_item_layout: Binary XML file line #17 in camapp.csfe.com:layout/abc_action_menu_item_layout: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #17 in camapp.csfe.com:layout/abc_action_menu_item_layout: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at androidx.appcompat.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:167)
        at androidx.appcompat.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:186)
        at androidx.appcompat.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:193)
        at androidx.appcompat.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:469)
        at androidx.appcompat.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1176)
        at androidx.appcompat.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
        at androidx.appcompat.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:226)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:292)
        at androidx.appcompat.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1063)
        at androidx.appcompat.view.menu.MenuBuilder.onItemActionRequestChanged(MenuBuilder.java:1113)
        at androidx.appcompat.view.menu.MenuItemImpl.setShowAsAction(MenuItemImpl.java:746)
        at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:475)
        at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:531)
        at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:207)
        at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:129)
        at androidx.appcompat.widget.Toolbar.inflateMenu(Toolbar.java:1193)
        at com.tuya.smart.jsbridge.base.webview.WebViewFragment.initViews(WebViewFragment.java:129)
        at com.tuya.smart.jsbridge.base.webview.WebViewFragment.onCreateView(WebViewFragment.java:111)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7923)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3332)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040017 a=-1}
        at android.content.res.TypedArray.getColorStateList(TypedArray.java:598)
        at android.widget.TextView.readTextAppearance(TextView.java:3969)
        at android.widget.TextView.<init>(TextView.java:1064)
        at android.widget.TextView.<init>(TextView.java:968)
        at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:100)
        at androidx.appcompat.view.menu.ActionMenuItemView.<init>(ActionMenuItemView.java:72)
        at androidx.appcompat.view.menu.ActionMenuItemView.<init>(ActionMenuItemView.java:68)
        	... 55 more
```

**Comment by Thewhitelight** [comment]
Do you use androidx.appcompat:appcompat ?
