### ISSUE TITLE
集成com.tuya.smart:tuyasmart-bizbundle-panel:3.27.5-4 报错

### ISSUE THREAD

**Issue by RothenL** [tuya/tuya-ui-bizbundle-android-demo#32]
集成这个UI SDK  没有写一行代码 打开程序报错
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzaa;
        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:742)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
国内市场用不上gms  要如何去掉？

**Comment by Innocencellh** [comment]
@RothenL Thank u for your question. Could u please provide your dependencies list of the app module ? Or maybe you only implement the 'com.tuya.smart:tuyasmart-bizbundle-panel:3.27.5-4' ?

**Comment by RothenL** [comment]
api 'com.tuya.smart:tuyasmart:3.28.5'  
    api files('libs/tuyasmart-lego_sdk_CENTRAL-0.0.8-central-1-rc.5.aar')
    implementation 'org.apache.commons:commons-io:1.3.2'
    implementation 'org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.61'
    implementation 'com.google.code.gson:gson:2.8.5'
    api 'com.alibaba:fastjson:1.1.67.android'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.8'
    implementation 'com.squareup.okhttp3:okhttp:3.9.0'
    implementation 'pub.devrel:easypermissions:2.0.1'

**Comment by Innocencellh** [comment]
@RothenL Thank u for your reply . I wonder how do you implement the "com.tuya.smart:tuyasmart-bizbundle-panel:3.27.5-4 "? I cant see the dependence above .

**Comment by RothenL** [comment]
"com.tuya.smart:tuyasmart-bizbundle-panel:3.27.5-4” in another module ，and i tested this sdk in a new project ,it works well ！I am puzzled where the problem is

**Comment by Innocencellh** [comment]
@RothenL Thank u for your reply . I cant reproduce . Could u please print your dependencies tree ,check if you have implemented something about firebase or google map ?
