### ISSUE TITLE
Unable to edit the device data using BizBundle

### ISSUE THREAD

**Issue by Ezaldeen99** [tuya/tuya-ui-bizbundle-android-demo#42]
## Problem description

When trying to use Bizbundle, After entering the device panel, everything is ok. However when clicking on edit device details like (name, icon, etc) an error appears and nothing happens

## SDK versions :

-              tuya_version = '3.36.0'

-              bizbundle_version = '3.34.5-9'
   
## Config files 

used these config files [tuya-ui-bizbundle-android-config-values](https://github.com/tuya/tuya-ui-bizbundle-android-config-values)

## Error Logs
```ModuleAppManager get module failed: com.tuya.device.base.info.DevBaseInfoModuleApp
    java.lang.ClassNotFoundException: Didn't find class "com.tuya.device.base.info.DevBaseInfoModuleApp" on path
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tuya.smart.framework.app.ModuleAppManager.getModuleAppByClass(ModuleAppManager.java:75)
        at com.tuya.smart.framework.app.ModuleAppManager.getModuleAppByTarget(ModuleAppManager.java:63)
        at com.tuya.smart.framework.router.SchemeServiceImpl.go(SchemeServiceImpl.java:215)
        at com.tuya.smart.framework.router.SchemeServiceImpl.access$000(SchemeServiceImpl.java:31)
        at com.tuya.smart.framework.router.SchemeServiceImpl$1.onContinue(SchemeServiceImpl.java:147)
        at com.tuya.smart.framework.service.RedirectServiceImpl.redirectUrl(RedirectServiceImpl.java:50)
        at com.tuya.smart.framework.router.SchemeServiceImpl.execute(SchemeServiceImpl.java:144)
        at com.tuya.smart.api.router.UrlRouter.execute(UrlRouter.java:57)
        at com.tuya.smart.panel.base.presenter.DevPanelMorePresenter.gotoDevBaseInfoActivity(DevPanelMorePresenter.java:1106)
        at com.tuya.smart.panel.base.presenter.DevPanelMorePresenter.onItemClick(DevPanelMorePresenter.java:381)
        at com.tuya.smart.panel.base.presenter.DevPanelMorePresenter.onItemClick(DevPanelMorePresenter.java:161)
        at com.tuya.smart.uispec.list.plug.text.clickable.Clickable$1.onClick(Clickable.java:16)```

**Comment by radishwu** [comment]
Do you import device detail, see https://developer.tuya.com/en/docs/app-development/devicedetails?id=Ka8tzzkq5fqbo.
