### ISSUE TITLE
Device details crash after updating

### ISSUE THREAD

**Issue by Ezaldeen99** [tuya/tuya-ui-bizbundle-android-demo#47]
after updating to sdk 5 and using the `thingMapping` I am facing this issue when entering device details from device panel 

logs 

```

 Process: ca.camscan.io, PID: 3268
ava.lang.RuntimeException: Unable to start activity ComponentInfo{ca.camscan.io/com.thingclips.smart.device_detail.DeviceDetailActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException
at com.thingclips.smart.archer.utils.ArcherSortUtils.getAllArcherSortBeans(ArcherSortUtils.kt:49)
at com.thingclips.smart.archer.ArcherListManager.getArcherSortList(ArcherListManager.kt:128)
at com.thingclips.smart.archer.ArcherListManager.<init>(ArcherListManager.kt:99)
at com.thingclips.smart.archer.ArcherListManager.<init>(ArcherListManager.kt:42)
at com.thingclips.smart.archer.ArcherListManager$Builder.build(ArcherListManager.kt:255)
at com.thingclips.smart.device_detail.DeviceDetailActivity.onCreate(DeviceDetailActivity.kt:142)
at android.app.Activity.performCreate(Activity.java:8051)
at android.app.Activity.performCreate(Activity.java:8031)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7839) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by linhuiluo** [comment]
@Ezaldeen99 You can add the following configuration under the main module ：
`configurations.all {
    resolutionStrategy {
        force 'com.thingclips.smart:thingsmart-archer:4.5.0-rc.5'
    }
}`

**Comment by Ezaldeen99** [comment]
Hello @linhuiluo  

this will give another error in grade build process

`
Failed to resolve: com.thingclips.smart:customlint:4.5.0-rc.1
Show in Project Structure dialog
Affected Modules: app
`

**Comment by linhuiluo** [comment]
@Ezaldeen99 I am sprry that .We have updated the new version ,maybe u can try add the following configuration under the main module ：
configurations.all { resolutionStrategy { force 'com.thingclips.smart:thingsmart-archer:4.5.0-rc.6' } }

**Comment by Ezaldeen99** [comment]
Thanks the last update works
