### ISSUE TITLE
Installing the application, crashes

### ISSUE THREAD

**Issue by denebchorny** [tuya/tuya-ui-bizbundle-android-demo#54]
Just clone the repo and running the app. It crashes.

`No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(android.content.Context, int, byte[], byte[], boolean) (tried Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative and Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative__Landroid_content_Context_2I_3B_3BZ)`

`FATAL EXCEPTION: main
                            Process: com.sample.sdk, PID: 11229
                            java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(android.content.Context, int, byte[], byte[], boolean) (tried Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative and Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative__Landroid_content_Context_2I_3B_3BZ)
                            	at com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(Native Method)
                            	at com.thingclips.smart.security.jni.JNICLibrary.doCommandNative(JNICLibrary.java:58)
                            	at com.thingclips.sdk.network.ThingNetworkSecurity.initJNI(ThingNetworkSecurity.java:9)
                            	at com.thingclips.smart.android.network.ThingSmartNetWork.initialize(ThingSmartNetWork.java:35)
                            	at com.thingclips.smart.sdk.ThingSdk.initThingData(ThingSdk.java:87)
                            	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:258)
                            	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:64)
                            	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:275)
                            	at com.thingclips.smart.home.sdk.ThingHomeSdk.init(ThingHomeSdk.java:111)
                            	at com.tuya.smart.bizubundle.demo.TuyaSmartApp.onCreate(TuyaSmartApp.java:33)
                            	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
                            	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
                            	at android.app.ActivityThread.access$1600(ActivityThread.java:310)
                            	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
                            	at android.os.Handler.dispatchMessage(Handler.java:106)
                            	at android.os.Looper.loopOnce(Looper.java:226)
                            	at android.os.Looper.loop(Looper.java:313)
                            	at android.app.ActivityThread.main(ActivityThread.java:8663)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

`win=Window{7c14a8f u0 Splash Screen com.sample.sdk EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=8 caller=com.android.server.wm.ActivityRecord.destroySurfaces:5841 com.android.server.wm.ActivityRecord.destroySurfaces:5822 com.android.server.wm.WindowState.onExitAnimationDone:5965 com.android.server.wm.ActivityRecord$$ExternalSyntheticLambda13.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.ActivityRecord.onAnimationFinished:7890 com.android.server.wm.ActivityRecord.postApplyAnimation:5572 `

**Comment by taojingGino** [comment]
@denebchorny Check whether the security component andimplementation fileTree(include: ['*.aar'], dir: 'libs')have been added to your project.

https://developer.tuya.com/en/docs/app-development/integrated?id=Ka69nt96cw0uj#id_security
